export const carMakes = [
  { id: 1, name: "Acura", abrv: "AC" },
  { id: 2, name: "Alfa Romeo", abrv: "AR" },
  { id: 3, name: "Aston Martin", abrv: "AM" },
  { id: 4, name: "Audi", abrv: "AD" },
  { id: 5, name: "Bentley", abrv: "BT" },
  { id: 6, name: "BMW", abrv: "BM" },
  { id: 7, name: "Buick", abrv: "BK" },
  { id: 8, name: "Cadillac", abrv: "CD" },
  { id: 9, name: "Chevrolet", abrv: "CH" },
  { id: 10, name: "Chrysler", abrv: "CY" },
  { id: 11, name: "Dodge", abrv: "DG" },
  { id: 12, name: "Ferrari", abrv: "FR" },
  { id: 13, name: "Fiat", abrv: "FT" },
  { id: 14, name: "Ford", abrv: "FD" },
  { id: 15, name: "Genesis", abrv: "GN" },
  { id: 16, name: "GMC", abrv: "GC" },
  { id: 17, name: "Honda", abrv: "HD" },
  { id: 18, name: "Hyundai", abrv: "HY" },
  { id: 19, name: "Infiniti", abrv: "IF" },
  { id: 20, name: "Jaguar", abrv: "JG" },
  { id: 21, name: "Jeep", abrv: "JP" },
  { id: 22, name: "Kia", abrv: "KA" },
  { id: 23, name: "Lamborghini", abrv: "LM" },
  { id: 24, name: "Land Rover", abrv: "LR" },
  { id: 25, name: "Lexus", abrv: "LX" },
  { id: 26, name: "Lincoln", abrv: "LN" },
  { id: 27, name: "Lotus", abrv: "LT" },
  { id: 28, name: "Maserati", abrv: "MS" },
  { id: 29, name: "Mazda", abrv: "MZ" },
  { id: 30, name: "McLaren", abrv: "ML" },
  { id: 31, name: "Mercedes-Benz", abrv: "MB" },
  { id: 32, name: "Mini", abrv: "MN" },
  { id: 33, name: "Mitsubishi", abrv: "MT" },
  { id: 34, name: "Nissan", abrv: "NS" },
  { id: 35, name: "Porsche", abrv: "PS" },
  { id: 36, name: "Ram", abrv: "RM" },
  { id: 37, name: "Rolls-Royce", abrv: "RR" },
  { id: 38, name: "Subaru", abrv: "SB" },
  { id: 39, name: "Suzuki", abrv: "SZ" },
  { id: 40, name: "Tesla", abrv: "TS" },
  { id: 41, name: "Toyota", abrv: "TY" },
  { id: 42, name: "Volkswagen", abrv: "VW" },
  { id: 43, name: "Volvo", abrv: "VL" },
];
